apiVersion: v1
kind: Pod
metadata:
  name: sample-downward-api
spec:
  containers:
  - image: nginx:1.16
    name: nginx-container
    volumeMounts:
    - name: downward-api-volume
      mountPath: /srv
  volumes:
  - name: downward-api-volume
    downwardAPI:
      items:
      - path: "podname"
        fieldRef:
          fieldPath: metadata.name
      - path: "cpu-request"
        resourceFieldRef:
          containerName: nginx-container
          resource: requests.cpu