apiVersion: v1
kind: LimitRange
metadata:
  name: sample-limitrange-container
  namespace: default
spec:
  limits:
  - type: Container
    default:
      memory: 256Mi
      cpu: 250m
    defaultRequest:
      memory: 128Mi
      cpu: 125m
    max:
      memory: 512Mi
      cpu: 500m
    min:
      memory: 64Mi
      cpu: 64m
    maxLimitRequestRatio:
      memory: 2
      cpu: 2