apiVersion: v1
kind: Pod
metadata:
  name: sample-emptydir-limmit
spec:
  containers:
  - image: nginx:1.16
    name: nginx-container
    volumeMounts:
    - mountPath: /cache
      name: cache-volume
  volumes:
  - name: cache-volume
    emptyDir:
      sizeLimit: 128Mi