apiVersion: v1
kind: PersistentVolume
metadata:
  name: sample-pv
  labels: # 레이블
    type: gce-pv
    enviroment: stg
spec:
  capacity: # 용량
    storage: 10Gi
  accessModes: # 접근 모드
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain # Reclaim Policy
  storageClassName: manual # StorageClass
  # PersistentVolume 플로그인별 설정(GCE Persistent Disk 예)
  gcePersistentDisk:
    pdName: k8s-disk
    fsType: ext4